Feat/harvester set editable by districts
technologiestiftung/kulturdaten-api pull request #102
Opened 2023-12-04 07:13 UTC by ThorstenDiekhof

All data from the district calendar now receives an editableBy with the associated district.

2023-12-04 11:06 UTC, herrherrmann requested changes
An sich werden die `editableBy`-Felder befüllt, allerdings verstehe ich die Logik dahinter noch nicht (s. Inline-Kommentar) und würde auf jeden Fall noch nahelegen, die `generateBoroughOfficeOrganizationID`-Funktion etwas aufzuräumen. :P

2023-12-04 11:06 UTC, herrherrmann commented on .env.example
> +MONGO_DB_PW=geh3im
Werden diese neuen Variablen irgend wo benutzt? Ich finde dazu nichts im Code. :D

2023-12-04 11:06 UTC, herrherrmann commented on src/utils/IDUtil.ts
> +	}
Ich verstehe noch nicht so ganz, was hier passieren soll. :D 

Momentan wird hier im Endeffekt der Bezirksname zu Großbuchstaben konvertiert, auf 13 Zeichen limitiert und alle O-Buchstaben im Bezirksnamen werden durch `1` ersetzt (weil der Buchstabe "O" in `allowedChars` fehlt).

Soll die ID wirklich so erzeugt werden? Und müssten wir nicht mit den echten Organization-IDs arbeiten, die während des Harvestings angelegt werden? 🤔

In jedem Fall würde ich versuchen, hier nur einen Loop zu verwenden, weil es ansonsten schwer zu verstehen ist. Und wahrscheinlich sollten wir `ID_LENGTH` verwenden, statt `13` hard zu coden.

2023-12-04 12:48 UTC, ThorstenDiekhof commented on .env.example
> +MONGO_DB_PW=geh3im
"noch" nicht... ;) ... Nein, Spaß beiseite, ist wirklich in den PR gerutscht, obwohl das schon in meiner .env vorhanden ist für einen anderen Branch und ich die example und meine abgeglichen habe. Das mach ich von Zeit zu Zeit... nehme das aber hier wieder raus...

2023-12-04 12:53 UTC, ThorstenDiekhof commented on src/utils/IDUtil.ts
> +	}
Ziel hier ist, eine ID zu haben, die sich jederzeit statisch generieren lässt und nur auf den erlaubten Zeichen basiert.

Diese ID wird auch beim Anlegen der Organisationen genutzt. Hier ist eine statische ID quasi die Referenz.

Wie der Loop organisiert wird, ist mir fast egal. 

Das mit der ID_LENGTH ist ein SEHR guter Einwand. Wird angepasst.

2023-12-04 13:08 UTC, ThorstenDiekhof commented on src/utils/IDUtil.ts
> +	}
Wenn du eine gute Idee hast, wie wir das ohne feste ID hinbekommen, sehr gerne. Ich würde es ungerne mit Namen usw. machen, da diese zu leicht zu ändern sind. Auch habe ich das Eintragen einer ID z.B. beim Harvester usw. zu unsauber empfunden. Bin da aber offen für Ideen.

2023-12-04 16:31 UTC, herrherrmann commented on src/utils/IDUtil.ts
> +	}
> Diese ID wird auch beim Anlegen der Organisationen genutzt.

Ah, aber das kommt dann in der Zukunft? Weil alle Organisationen ja momentan noch eine zufällige ID über `generateOrganizationID()` bekommen. (Außer, ich übersehe irgend wo etwas?)

> Wenn du eine gute Idee hast, wie wir das ohne feste ID hinbekommen, sehr gerne.

Ich dachte ursprünglich, dass wir im DistrictDataMapper die erstellten/existierenden Organisationen anschauen und dann für das `editableBy`-Feld den `identifier` der passenden Bezirks-Organization raussuchen (wir könnten z.B. dafür die `bezirk_id` in `metadata` mitspeichern).

Wenn du erstmal beim aktuell verwendeten System bleiben möchtest, würde ich zumindest noch das "O" in der Liste `allowedChars` ergänzen. Denn ich finde es sehr überraschend, dass wir alle Os mit der Zahl 1 ersetzen. :D

2023-12-05 06:45 UTC, ThorstenDiekhof commented on src/utils/IDUtil.ts
> +	}
Problem ist, dass wir nicht alle Organisationen erstellen. Wenn wir mit Harvesting neue Events einladen, gibt es alle Organisationen dazu schon. Wir müssen die ID dort quasi irgendwo vorhalten oder eben die Organisation nach anderen Kriterien finden. Wir können irgendwo jedem der Organisationen eine feste ID vergeben - das kann aber dazu führen, dass diese nicht konform mit dem ID String ist, da dieser von den Werten in env abhängt. Daher ist es einfacher einen klaren Algorithmus zu haben, der aus einem Bezirksnamen ein erlaubten ID-String macht. 

Zur ersten Frage: Ja! Der selbe Algorithmus wurd auch in einer anderen Branch genutzt. Vor 3 Monaten hätte ich das noch alles in eine Branch gepackt, da es aufeinander aufbaut. Jetzt bin ich dabei zu versuchen die Branches getrennt zu lassen. -> **Learning für mich:** So eine Abhängigkeit und so ein Zusammenhang muss ich im PR beschreiben!

 Zum 0. Nein ich meine, zum O. Also kein 0 sondern ein O - oder doch lieber ein 0? Die ID ist nicht primär für das Lesen und Verstehen von Menschen gemacht. ABER, sie ist so aufgebaut, dass man sie notfalls z.B. am Telefon oder so durchgeben kann. Wenn irgendwann jemand den Support anruft und die URL vorlesen muss z.B. Ich habe daher alle die typischen Kandidaten für Verwechsler beim Vorlesen herausgelassen.

2023-12-06 15:24 UTC, herrherrmann commented on src/utils/IDUtil.ts
> +	}
Ah ok, so langsam verstehe ich, was hier passiert. :D Danke für die Erklärung. Wenn der Algorithmus so gewünscht ist, passt der Code auch so!

2023-12-06 15:25 UTC, herrherrmann approved these changes
Mit dem Kontext, dass `getBoroughOfficeOrganizationID` irgend wann auch bei der Erstellung der Bezirks-spezifischen Organizations benutzt wird, macht das jetzt Sinn für mich!

2023-12-12 07:09 UTC, merged