Feat/editable by filter
technologiestiftung/kulturdaten-api pull request #104
Opened 2023-12-05 12:48 UTC by ThorstenDiekhof

Location, Attraction, Event und Organization können jetzt per editableBy Path-Tag gefiltert werden. Hierbei gilt:

Es werden nur die Daten ausgegeben, die die OrganizationId des Felds editableBy im Array metadata.editableBy stehen haben.

Sind andere Filter aktiv, wird default eine UND Verknüpfung vorgenommen.

Nebenbei habe ich für Events noch die Filter byLocation und byAttraction implementiert, da dies "auf dem Weg" lag. Können durch diese Filter die GET admin/attractions Route überflüssig werden? Bin mir da nicht ganz sicher.

2023-12-06 15:22 UTC, herrherrmann requested changes
Nice! Habe auch alle Filter kurz getestet und sie funktionieren. 👍 

Habe noch ein paar optionale Inline-Kommenare hinterlassen. Könnte man auch später refactoren.

Und es gibt noch eine Linter-Warnung in `OrganizationsController.tts`, wie’s aussieht.

> Können durch diese Filter die GET admin/attractions Route überflüssig werden? Bin mir da nicht ganz sicher.

Leider noch nicht zu 100 %, denn die `GET admin/attractions`-Route lädt ja auch für jede Attraction die passenden Events (damit da keine Request-Kaskade entsteht).

2023-12-06 15:22 UTC, herrherrmann commented on src/resources/attractions/controllers/AttractionsController.ts
> +	}
Diese neuen Filterfunktionen könnte man alle noch `private` machen, weil sie ja nur innerhalb dieses Controllers verwendet werden.

2023-12-06 15:22 UTC, herrherrmann commented on src/common/parameters/Params.ts
> +};
Da wir `asReference` und `editableBy` eigentlich immer dabei haben, könnte man überlegen, die hier auch zu hinterlegen (statt es komplett offen zu lassen).

```suggestion
export type Params = {
	asReference: string;
	editableBy: string;
	[key: string]: string;
};
```

2023-12-06 15:22 UTC, herrherrmann commented on src/resources/events/controllers/EventsController.ts
> +	getEditableByFilter(editableBy?: string) {
Statt diese Funktion an 4 verschiedenen Stellen zu definieren, könnte man diese auch mit in die `MetadataUtils` packen. 💡

2023-12-07 06:53 UTC, ThorstenDiekhof commented on src/resources/attractions/controllers/AttractionsController.ts
> +	}
Jep. Hier muss ich eh mal konsequent sein. Manche Methoden sind public, andere gar nicht gekennzeichnet...

2023-12-07 06:55 UTC, ThorstenDiekhof commented on src/common/parameters/Params.ts
> +};
Das hatte ich überlegt und eine Version beinhaltete auch feste Werte. Die Parameter asReference und editableBy sind nur bei diesen GET Routen Standard. Andere Routen werden Parameter bekommen, die diese nicht beinhalten.

Daher habe ich es erstmal komplett frei gelassen.

2023-12-07 07:02 UTC, ThorstenDiekhof commented on src/resources/events/controllers/EventsController.ts
> +	getEditableByFilter(editableBy?: string) {
Ja. Ich bin gedanklich dabei, eine "Filter-Fabrik" zu designen. Da werde ich alle Filter hin auslagern - auch, weil ich nicht möchte, dass die Controller / Services usw. "Mongo-DB" Sprache sprechen. Das selbe dann für Projektionen. 

Bis dahin habe ich die function mal ins MetadataUtil verlagert.

2023-12-07 09:56 UTC, herrherrmann approved these changes
Supi!

2023-12-07 10:45 UTC, merged