Feat/owner is set automatically
technologiestiftung/kulturdaten-api pull request #92
Opened 2023-11-14 10:27 UTC by ThorstenDiekhof

Folgender Algorithmus sollte angewendet werden:

Wenn ein User eine Location/Attraction/Event anlegt, 
wird der manager/curator/organizer jeweils durch die Organisation des Users ersetzt.

Wenn es kein User gibt, wird das Feld gelöscht (was nach den aktuellen Berechtigungen nicht erlaubt ist)

Wenn der User ein SuperAdmin ist, wird das Feld nur dann durch die Organisation des Users ersetzt, wenn das Feld beim Anlegen leer ist. Somit können SuperAdmins für jeden Daten anlegen.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205879063684604

2023-11-15 13:28 UTC, herrherrmann requested changes
Sehr cool! Funktioniert soweit, habe es lokal getestet. Habe noch ein paar Inline-Kommentare hinterlassen.

Und, um Attractions im neuen Format (mit gefülltem `curator`-Feld) richtig im Frontend zu laden, müsste noch das Model `AdminAttraction` angepasst werden (dort fehlt das `curator`-Feld noch, weswegen die Response Validation dann fehlschlägt).

2023-11-15 13:28 UTC, herrherrmann commented on src/resources/attractions/services/AttractionsService.ts
> +		if (!authUser && !isSuperAdmin(authUser)) {
Diese Abfrage verstehe ich nicht ganz. Der zweite Teil (`!isSuperAdmin(authUser)`) ist doch eh immer `false`, wenn es eh keinen `authUser` gibt, oder?

2023-11-15 13:28 UTC, herrherrmann commented on src/schemas/models/CreateEventRequest.yml
> -  - organizer
Wahrscheinlich können wir `organizer` jetzt auch völlig aus dem Request entfernen, wenn es eh serverseitig gesetzt wird, oder? 🤔 Oder möchtest du es für eine potenzielle Zukunft behalten, in der man Events für _andere_ Organisationen anlegen kann?

2023-11-15 13:28 UTC, herrherrmann commented on src/schemas/models/CreateAttractionRequest.yml
> +    $ref: "Reference.yml"
Ähnliche Frage wie bei `CreateEventRequest.yml`: Wieso erlauben wir hier, einen `curator` anzugeben, wenn dieses Feld eh immer serverseitig überschrieben wird?

2023-11-15 13:56 UTC, ThorstenDiekhof commented on src/resources/attractions/services/AttractionsService.ts
> +		if (!authUser && !isSuperAdmin(authUser)) {
ups! Das sollte ein || sein... jetzt bin ich am grübeln, wieso meine Tests trotzdem geklappt haben. Wenn es keinen User gibt ODER der Nutzer kein SuperAdmin ist, dann soll das Feld gelöscht werden. 
Danke für die Genauigkeit

2023-11-15 13:57 UTC, ThorstenDiekhof commented on src/schemas/models/CreateEventRequest.yml
> -  - organizer
Ein SuperAdmin kann auch einen "fremden" Organizer setzen. 
Das ist aktuell der einzige Grund, das drin zu lassen.
wenn wir eigene "SuperAdmin"-Tools bauen kann das raus.

2023-11-15 13:57 UTC, ThorstenDiekhof commented on src/schemas/models/CreateAttractionRequest.yml
> +    $ref: "Reference.yml"
Siehe oberen Kommentar.

2023-11-20 09:40 UTC, herrherrmann requested changes
Nice, jetzt macht die Abfrage mehr Sinn für mich! :D 

Dieser Part fehlt ggf. noch (stand in meinem vorigen Kommentar)?

> Um Attractions im neuen Format (mit gefülltem curator-Feld) richtig im Frontend zu laden, müsste noch das Model `AdminAttraction` angepasst werden (dort fehlt das curator-Feld noch, weswegen die Response Validation dann fehlschlägt).

2023-11-20 12:40 UTC, herrherrmann approved these changes
Alles gut nun! Habe es auch nochmal lokal getestet.

2023-11-20 13:47 UTC, merged